name: Build Android Binary

on:
  push:
    paths:
      - zuto.cc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r26d

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Build the project
      run: |
        ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my_program
        path: obj/local/arm64-v8a/my_program
