name: Build ARM Binary

on:
  push:
    paths:
      - zuto.cc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install ARM GCC Toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf

    - name: Build the project
      run: |
        mkdir -p build
        cd build
        arm-linux-gnueabihf-g++ -o my_program ../zuto.cc

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my_program
        path: build/my_program
